### ISSUE TITLE
Patient data load fail On a Redshift schema with CMSDESynPUF100k

### ISSUE THREAD

**Issue by dxciberaws** [BenGlicksberg/PatientExploreR#8]
Hi

I have a Redshift database with the CMSDESynPUF100K schema (also with Achilles installed). After solving a connection issue (see my PR about that), I get this error when loading a patient's data from a patient search result:

Warning: Error in rbindlist: Class attribute on column 2 of item 3 does not match with column 2 of item 1.
  80: rbindlist
  79: data.table::.rbind.data.table
  78: rbind
  77: rbind
  76: generate_pt_report
  72: observeEventHandler [/srv/shiny-server/PatientExploreR/app.R#2027]
   1: runApp

Execution halted

Any ideas?

**Comment by evs2008** [comment]
This is the same error I opened as #6, no?

**Comment by dxciberaws** [comment]
Yes, it looks like the same, I'll close this ticket and track yours.

Thanks
